
@startuml



package "indexer" {
    component "index"
    component "tokenizer"
    component "sort"
    component "merge"
}

package "index searcher" {
    component "query"
}

package "index manager" {
    component "writer"
    component "reader"
}

package "document manager"


[indexer] --> [index manager]
[indexer] --> [document manager]
[index manager] --> [index searcher]
[document manager] --> [index searcher]

@enduml
